### PR TITLE
Add a script to check missing attribute

### PR DESCRIPTION
**Pull request by Mogztter**
I've added two scripts:

`./build.sh`

This script will basically run `npm run build`. The stderr will be sent to the console and to the file `build-stderr.log`.

`./lint/asciidoctor-warnings.sh`

This script will read the file `build-stderr.log` and display an informative message.
If the `build-stderr.log` contains "skipping reference to missing attribute", it will exit with an exit code 1.

The current output is:

```console
$ ./lint/asciidoctor-warnings.sh
Found 294 unresolved attributes
Unresolved attribute {assignedlabels} found in:
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.nodesByLabel/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {batch} found in:
  labs/kafka/4.0/kafka-connect/index.html
Unresolved attribute {_batch} found in:
  labs/apoc/4.1/graph-updates/periodic-execution/index.html
  labs/apoc/4.0/graph-updates/periodic-execution/index.html
Unresolved attribute {conf} found in:
  labs/apoc/4.1/comparing-graphs/fingerprinting/index.html
  labs/apoc/4.0/comparing-graphs/fingerprinting/index.html
Unresolved attribute {config} found in:
  labs/apoc/4.1/cypher-execution/run-cypher-scripts/index.html
  labs/apoc/4.1/virtual/nodes-collapse/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/import/xls/index.html
  labs/apoc/4.1/import/html/index.html
  labs/apoc/4.1/import/web-apis/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.csv/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.xls/index.html
  labs/apoc/4.1/overview/apoc.meta/apoc.meta.data/index.html
  labs/apoc/4.1/overview/apoc.meta/apoc.meta.schema/index.html
  labs/apoc/4.1/overview/apoc.meta/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
  labs/apoc/4.1/graph-updates/graph-refactoring/merge-nodes/index.html
  labs/apoc/4.0/cypher-execution/run-cypher-scripts/index.html
  labs/apoc/4.0/virtual/nodes-collapse/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/import/xls/index.html
  labs/apoc/4.0/import/html/index.html
  labs/apoc/4.0/import/web-apis/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.csv/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.xls/index.html
  labs/apoc/4.0/overview/apoc.meta/apoc.meta.data/index.html
  labs/apoc/4.0/overview/apoc.meta/apoc.meta.schema/index.html
  labs/apoc/4.0/overview/apoc.meta/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.0/graph-updates/graph-refactoring/merge-nodes/index.html
Unresolved attribute {connectionmap} found in:
  labs/apoc/4.1/database-integration/load-ldap/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.0/database-integration/load-ldap/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {creatednodes} found in:
  labs/apoc/4.1/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.1/overview/apoc.trigger/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {data} found in:
  labs/apoc/4.1/overview/apoc.map/apoc.map.updateTree/index.html
  labs/apoc/4.1/overview/apoc.map/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.0/overview/apoc.map/apoc.map.updateTree/index.html
  labs/apoc/4.0/overview/apoc.map/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/data-structures/map-functions/index.html
Unresolved attribute {deletednodes} found in:
  labs/apoc/4.1/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.1/overview/apoc.trigger/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {duration} found in:
  labs/apoc/4.1/misc/utility-functions/index.html
  labs/apoc/4.0/misc/utility-functions/index.html
Unresolved attribute {environment} found in:
  labs/kafka/4.0/cud-file-format/index.html
  labs/kafka/4.0/sink-strategies/index.html
  labs/kafka/4.0/consumer-configuration/index.html
Unresolved attribute {events} found in:
  labs/kafka/4.0/streams/index.html
  labs/kafka/4.0/consumer/index.html
Unresolved attribute {first} found in:
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.0/data-structures/map-functions/index.html
Unresolved attribute {id} found in:
  developer/spring-data-neo4j-rx/index.html
  developer/movie-database/index.html
  labs/kafka/4.0/cud-file-format/index.html
Unresolved attribute {json} found in:
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/overview/apoc.json/apoc.json.path/index.html
  labs/apoc/4.1/overview/apoc.json/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/overview/apoc.json/apoc.json.path/index.html
  labs/apoc/4.0/overview/apoc.json/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
Unresolved attribute {maps} found in:
  labs/apoc/4.1/overview/apoc.map/apoc.map.mergeList/index.html
  labs/apoc/4.1/overview/apoc.map/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.0/overview/apoc.map/apoc.map.mergeList/index.html
  labs/apoc/4.0/overview/apoc.map/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/data-structures/map-functions/index.html
Unresolved attribute {nodeoperators} found in:
  labs/apoc/4.1/virtual/graph-grouping/index.html
  labs/apoc/4.0/virtual/graph-grouping/index.html
Unresolved attribute {params} found in:
  labs/apoc/4.1/cypher-execution/cypher-multiple-statements/index.html
  labs/apoc/4.1/cypher-execution/running-cypher/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/export/csv/index.html
  labs/apoc/4.1/export/json/index.html
  labs/apoc/4.1/overview/apoc.cypher/index.html
  labs/apoc/4.1/overview/apoc.cypher/apoc.cypher.runTimeboxed/index.html
  labs/apoc/4.1/overview/apoc.cypher/apoc.cypher.runMany/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.json.query/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.xls.query/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.csv.query/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.0/cypher-execution/cypher-multiple-statements/index.html
  labs/apoc/4.0/cypher-execution/running-cypher/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/export/csv/index.html
  labs/apoc/4.0/export/json/index.html
  labs/apoc/4.0/overview/apoc.cypher/index.html
  labs/apoc/4.0/overview/apoc.cypher/apoc.cypher.runTimeboxed/index.html
  labs/apoc/4.0/overview/apoc.cypher/apoc.cypher.runMany/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.json.query/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.xls.query/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.csv.query/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromCypher/index.html
Unresolved attribute {price} found in:
  labs/kafka/4.0/kafka-connect/index.html
  labs/kafka/4.0/streams/index.html
  labs/kafka/4.0/sink-strategies/index.html
  labs/kafka/4.0/consumer/index.html
Unresolved attribute {properties} found in:
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromPath/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromData/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromPaths/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDB/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.from/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromPath/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromData/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromPaths/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDB/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.from/index.html
Unresolved attribute {reloperators} found in:
  labs/apoc/4.1/virtual/graph-grouping/index.html
  labs/apoc/4.0/virtual/graph-grouping/index.html
Unresolved attribute {removedlabels} found in:
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.nodesByLabel/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {_retry} found in:
  labs/apoc/4.1/graph-updates/periodic-execution/index.html
  labs/apoc/4.0/graph-updates/periodic-execution/index.html
Unresolved attribute {searchmap} found in:
  labs/apoc/4.1/database-integration/load-ldap/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.0/database-integration/load-ldap/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {second} found in:
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.0/data-structures/map-functions/index.html
Unresolved attribute {url} found in:
  developer/movie-database/index.html
  labs/apoc/4.1/import/xls/index.html
  labs/apoc/4.1/import/load-csv/index.html
  labs/apoc/4.0/import/xls/index.html
  labs/apoc/4.0/import/load-csv/index.html
```

Since Asciidoctor/Antora does not give us the AsciiDoc source for a missing attribute, I'm using `grep` on the `build/site` directory.
So, it might contain a few false-positive but overall I think it gives us a good idea of where we should look.

Once #8 is merged, I will update this pull request to run this script when `npm run lint` is executed.

### CODE REVIEW

**Comment by Mogztter** [comment]
Rebased on master and we are down to 135 unresolved attributes:

```
Found 135 unresolved attributes
Unresolved attribute {_batch} found in:
  labs/apoc/4.0/graph-updates/periodic-execution/index.html
  labs/apoc/4.1/graph-updates/periodic-execution/index.html
Unresolved attribute {_retry} found in:
  labs/apoc/4.0/graph-updates/periodic-execution/index.html
  labs/apoc/4.1/graph-updates/periodic-execution/index.html
Unresolved attribute {assignedlabels} found in:
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.nodesByLabel/index.html
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {conf} found in:
  labs/apoc/4.0/comparing-graphs/fingerprinting/index.html
  labs/apoc/4.1/comparing-graphs/fingerprinting/index.html
Unresolved attribute {config} found in:
  labs/apoc/4.0/import/xls/index.html
  labs/apoc/4.0/import/html/index.html
  labs/apoc/4.0/import/web-apis/index.html
  labs/apoc/4.0/graph-updates/graph-refactoring/merge-nodes/index.html
  labs/apoc/4.0/cypher-execution/run-cypher-scripts/index.html
  labs/apoc/4.0/virtual/nodes-collapse/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/overview/apoc.meta/apoc.meta.data/index.html
  labs/apoc/4.0/overview/apoc.meta/apoc.meta.schema/index.html
  labs/apoc/4.0/overview/apoc.meta/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.csv/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/apoc.load/apoc.load.xls/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.1/import/xls/index.html
  labs/apoc/4.1/import/html/index.html
  labs/apoc/4.1/import/web-apis/index.html
  labs/apoc/4.1/graph-updates/graph-refactoring/merge-nodes/index.html
  labs/apoc/4.1/cypher-execution/run-cypher-scripts/index.html
  labs/apoc/4.1/virtual/nodes-collapse/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/overview/apoc.meta/apoc.meta.data/index.html
  labs/apoc/4.1/overview/apoc.meta/apoc.meta.schema/index.html
  labs/apoc/4.1/overview/apoc.meta/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.csv/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.xls/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
Unresolved attribute {connectionmap} found in:
  labs/apoc/4.0/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/database-integration/load-ldap/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/database-integration/load-ldap/index.html
Unresolved attribute {creatednodes} found in:
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.1/overview/apoc.trigger/index.html
  labs/apoc/4.1/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.1/overview/index.html
Unresolved attribute {data} found in:
  labs/apoc/4.0/data-structures/map-functions/index.html
  labs/apoc/4.0/overview/apoc.map/apoc.map.updateTree/index.html
  labs/apoc/4.0/overview/apoc.map/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.1/overview/apoc.map/apoc.map.updateTree/index.html
  labs/apoc/4.1/overview/apoc.map/index.html
  labs/apoc/4.1/overview/index.html
Unresolved attribute {deletednodes} found in:
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.1/overview/apoc.trigger/index.html
  labs/apoc/4.1/overview/apoc.trigger/apoc.trigger.add/index.html
  labs/apoc/4.1/overview/index.html
Unresolved attribute {duration} found in:
  labs/apoc/4.0/misc/utility-functions/index.html
  labs/apoc/4.1/misc/utility-functions/index.html
Unresolved attribute {first} found in:
  labs/apoc/4.0/data-structures/map-functions/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
Unresolved attribute {json} found in:
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/overview/apoc.json/apoc.json.path/index.html
  labs/apoc/4.0/overview/apoc.json/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/overview/apoc.json/apoc.json.path/index.html
  labs/apoc/4.1/overview/apoc.json/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.validateDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDocument/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
Unresolved attribute {maps} found in:
  labs/apoc/4.0/data-structures/map-functions/index.html
  labs/apoc/4.0/overview/apoc.map/apoc.map.mergeList/index.html
  labs/apoc/4.0/overview/apoc.map/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
  labs/apoc/4.1/overview/apoc.map/apoc.map.mergeList/index.html
  labs/apoc/4.1/overview/apoc.map/index.html
  labs/apoc/4.1/overview/index.html
Unresolved attribute {nodeoperators} found in:
  labs/apoc/4.0/virtual/graph-grouping/index.html
  labs/apoc/4.1/virtual/graph-grouping/index.html
Unresolved attribute {params} found in:
  labs/apoc/4.0/cypher-execution/cypher-multiple-statements/index.html
  labs/apoc/4.0/cypher-execution/running-cypher/index.html
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/export/json/index.html
  labs/apoc/4.0/export/csv/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.xls.query/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.csv.query/index.html
  labs/apoc/4.0/overview/apoc.export/apoc.export.json.query/index.html
  labs/apoc/4.0/overview/apoc.cypher/apoc.cypher.runMany/index.html
  labs/apoc/4.0/overview/apoc.cypher/apoc.cypher.runTimeboxed/index.html
  labs/apoc/4.0/overview/apoc.cypher/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.1/cypher-execution/cypher-multiple-statements/index.html
  labs/apoc/4.1/cypher-execution/running-cypher/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/export/json/index.html
  labs/apoc/4.1/export/csv/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.xls.query/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.csv.query/index.html
  labs/apoc/4.1/overview/apoc.export/apoc.export.json.query/index.html
  labs/apoc/4.1/overview/apoc.cypher/apoc.cypher.runMany/index.html
  labs/apoc/4.1/overview/apoc.cypher/apoc.cypher.runTimeboxed/index.html
  labs/apoc/4.1/overview/apoc.cypher/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
Unresolved attribute {properties} found in:
  labs/apoc/4.0/virtual/virtual-graph/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromData/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromPath/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromDB/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.from/index.html
  labs/apoc/4.0/overview/apoc.graph/index.html
  labs/apoc/4.0/overview/apoc.graph/apoc.graph.fromPaths/index.html
  labs/apoc/4.1/virtual/virtual-graph/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromData/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromCypher/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromPath/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromDB/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.from/index.html
  labs/apoc/4.1/overview/apoc.graph/index.html
  labs/apoc/4.1/overview/apoc.graph/apoc.graph.fromPaths/index.html
Unresolved attribute {reloperators} found in:
  labs/apoc/4.0/virtual/graph-grouping/index.html
  labs/apoc/4.1/virtual/graph-grouping/index.html
Unresolved attribute {removedlabels} found in:
  labs/apoc/4.0/overview/apoc.trigger/apoc.trigger.nodesByLabel/index.html
  labs/apoc/4.0/overview/apoc.trigger/index.html
  labs/apoc/4.0/overview/index.html
Unresolved attribute {searchmap} found in:
  labs/apoc/4.0/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.0/overview/apoc.load/index.html
  labs/apoc/4.0/overview/index.html
  labs/apoc/4.0/database-integration/load-ldap/index.html
  labs/apoc/4.1/overview/apoc.load/apoc.load.ldap/index.html
  labs/apoc/4.1/overview/apoc.load/index.html
  labs/apoc/4.1/overview/index.html
  labs/apoc/4.1/database-integration/load-ldap/index.html
Unresolved attribute {second} found in:
  labs/apoc/4.0/data-structures/map-functions/index.html
  labs/apoc/4.1/data-structures/map-functions/index.html
Unresolved attribute {url} found in:
  developer/movie-database/index.html
  labs/apoc/4.0/import/xls/index.html
  labs/apoc/4.0/import/load-csv/index.html
  labs/apoc/4.1/import/xls/index.html
  labs/apoc/4.1/import/load-csv/index.html
```

**Comment by adam-cowley** [comment]
@mneedham Are these part of the auto-generated docs?  Anything we could fix quickly?

**Comment by adam-cowley** [comment]
I'm guessing this has been superseded in some way? 

```
> @antora/ui-default@ start /Users/adam/projects/docs/ui
> LIVERELOAD=true gulp preview

[10:57:40] Using gulpfile ~/projects/docs/ui/gulpfile.js
[10:57:40] Starting 'preview'...
[10:57:40] Starting 'build'...
[10:57:40] Starting 'preview:build-pages'...
[10:57:41] gulp-imagemin: Minified 12 images (saved 26.5 kB - 75.1%)
[10:57:41] Finished 'preview:build-pages' after 1.4 s
[10:57:41] The following tasks did not complete: preview, <parallel>, build
[10:57:41] Did you forget to signal async completion?
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Cannot read property 'getPages' of undefined in UI template src/layouts/default.hbs
ned
    at Object.module.exports (<anonymous>:5:32)
    at Object.wrapper (/Users/adam/projects/docs/ui/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (/Users/adam/projects/docs/ui/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:15:159)
```

**Comment by Mogztter** [comment]
I've rebased on master, I cannot reproduce the error :thinking:

**Pull request merged**
