### PR TITLE
Integrate the Knowledge Base

### PR DESCRIPTION
**Pull request by Mogztter**
Since the KB documentation site is generated inside `/developer` (to preserve the current hierarchy), you will need to build the developer documentation site first using:

```
npm run build:unversioned
```

Then, you can use the following command to build the Knowledge Base:

```
antora kb.yml
```

### Index page

`developer/kb`

localhost_8000_developer_kb_(Laptop with MDPI screen)

### Article pages

`/developer/kb/a-demonstration-of-causal-cluster-routing`

localhost_8000_developer_kb_a-demonstration-of-causal-cluster-routing_(Laptop with MDPI screen)

`/developer/kb/neo4j-supported-versions`

localhost_8000_developer_kb_neo4j-supported-versions_(Laptop with MDPI screen)

###  List of articles with the tag "authentication"

`developer/kb/tags/?tag=authentication`

localhost_8000_developer_kb_tags__tag=authentication(Laptop with MDPI screen)

### List of articles with the category "desktop"

`developer/kb/categories/?category=desktop`

localhost_8000_developer_kb_categories__category=desktop(Laptop with MDPI screen) (1)

//cc @jexp @adam-cowley

### CODE REVIEW

**Comment by Mogztter** [comment]
Ping @spgandhi

**Comment by spgandhi** [comment]
I'll take a look at this sometime this week @Mogztter

**Comment by Mogztter** [comment]
I've updated the design of the article page:

kb-article

**Comment by Mogztter** [comment]
Remember to update the source once https://github.com/neo4j-documentation/knowledge-base/pull/27 is merged

**Comment by Mogztter** [comment]
@adam-cowley Rebased on master

**Pull request merged**
